name: Deploy to VM

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build React Application
        run: |
          npm install
          npm run build
      - name: Compress Build Folder
        run: |
          tar -czf dist.tar.gz -C ./dist .
      - name: Transfer Docker Image to VM and Run
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./build.tar.gz
          target: /frontendapp