name: Deploy to VM

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Transfer Docker Image to VM and Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git clone https://github.com/ragunanthan/timeSheetFrontend.git
            cd timeSheetFrontend
            ls
            docker build -t frontendapp:latest .
            docker run -d -p 80:3000 frontendapp:latest