name: Deploy to VM

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t frontendapp:tag .

      - name: Save Docker Image to Tar
        run: docker save -o frontendapp.tar frontendapp:tag

      - name: Transfer Docker Image to VM and Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /tmp/docker_images
            scp -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no frontendapp.tar ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/tmp/docker_images/

            # Connect to VM and load Docker image
            ssh -i $HOME/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'docker load -i /tmp/docker_images/frontendapp.tar'
            docker run -d -p 80:3000 frontendapp:tag